<?php
/*

INCLUSAO E BAIXA DE TITULOS

 */

require_once "vendor/autoload.php";
use \Kanoah\BD\SQLServer;

$_SESSION["SERVER"] = "SPON019400250";
$_SESSION["DATABASE"] = "P12127MNTDBEXP";
$_SESSION["USER"] = "sa";
$_SESSION["PASSWORD"] = "1234";

try {
    $sql = new SQLServer();
} catch (Exception $e) {
    unset($_SESSION["SERVER"]);
    unset($_SESSION["DATABASE"]);
    unset($_SESSION["USER"]);
    unset($_SESSION["PASSWORD"]);
}

for ($i = 1; $i < 15000; $i++) {
    $recno = $i;

    try {
        $sql->query("
		INSERT [dbo].[SE1T10]
				([E1_FILIAL],
				[E1_PREFIXO],
				[E1_NUM],
				[E1_PARCELA],
				[E1_TIPO],
				[E1_NATUREZ],
				[E1_PORTADO],
				[E1_AGEDEP],
				[E1_CLIENTE],
				[E1_LOJA],
				[E1_NOMCLI],
				[E1_EMISSAO],
				[E1_VENCTO],
				[E1_VENCREA],
				[E1_VALOR],
				[E1_BASEIRF],
				[E1_ISS],
				[E1_IRRF],
				[E1_NUMBCO],
				[E1_INDICE],
				[E1_BAIXA],
				[E1_NUMBOR],
				[E1_DATABOR],
				[E1_EMIS1],
				[E1_HIST],
				[E1_LA],
				[E1_LOTE],
				[E1_MOTIVO],
				[E1_MOVIMEN],
				[E1_OP],
				[E1_SITUACA],
				[E1_CONTRAT],
				[E1_SALDO],
				[E1_SUPERVI],
				[E1_VEND1],
				[E1_VEND2],
				[E1_VEND3],
				[E1_VEND4],
				[E1_VEND5],
				[E1_COMIS1],
				[E1_COMIS2],
				[E1_COMIS3],
				[E1_COMIS4],
				[E1_DESCONT],
				[E1_COMIS5],
				[E1_MULTA],
				[E1_JUROS],
				[E1_CORREC],
				[E1_VALLIQ],
				[E1_VENCORI],
				[E1_CONTA],
				[E1_VALJUR],
				[E1_PORCJUR],
				[E1_MOEDA],
				[E1_BASCOM1],
				[E1_BASCOM2],
				[E1_BASCOM3],
				[E1_BASCOM4],
				[E1_BASCOM5],
				[E1_FATPREF],
				[E1_FATURA],
				[E1_OK],
				[E1_PROJETO],
				[E1_CLASCON],
				[E1_VALCOM1],
				[E1_VALCOM2],
				[E1_VALCOM3],
				[E1_VALCOM4],
				[E1_VALCOM5],
				[E1_OCORREN],
				[E1_INSTR1],
				[E1_INSTR2],
				[E1_PEDIDO],
				[E1_DTVARIA],
				[E1_VARURV],
				[E1_VLCRUZ],
				[E1_DTFATUR],
				[E1_NUMNOTA],
				[E1_SERIE],
				[E1_STATUS],
				[E1_ORIGEM],
				[E1_IDENTEE],
				[E1_NUMCART],
				[E1_FLUXO],
				[E1_DESCFIN],
				[E1_DIADESC],
				[E1_TIPODES],
				[E1_CARTAO],
				[E1_CARTVAL],
				[E1_CARTAUT],
				[E1_ADM],
				[E1_VLRREAL],
				[E1_TRANSF],
				[E1_BCOCHQ],
				[E1_AGECHQ],
				[E1_CTACHQ],
				[E1_NUMLIQ],
				[E1_ORDPAGO],
				[E1_RECIBO],
				[E1_INSS],
				[E1_FILORIG],
				[E1_DTACRED],
				[E1_TIPOFAT],
				[E1_TIPOLIQ],
				[E1_CSLL],
				[E1_COFINS],
				[E1_PIS],
				[E1_FLAGFAT],
				[E1_MESBASE],
				[E1_ANOBASE],
				[E1_PLNUCOB],
				[E1_CODEMP],
				[E1_CODINT],
				[E1_MATRIC],
				[E1_TXMOEDA],
				[E1_ACRESC],
				[E1_SDACRES],
				[E1_DECRESC],
				[E1_SDDECRE],
				[E1_MULTNAT],
				[E1_MSFIL],
				[E1_MSEMP],
				[E1_PROJPMS],
				[E1_DESDOBR],
				[E1_NRDOC],
				[E1_MODSPB],
				[E1_EMITCHQ],
				[E1_IDCNAB],
				[E1_PLCOEMP],
				[E1_PLTPCOE],
				[E1_CODCOR],
				[E1_PARCCSS],
				[E1_CODORCA],
				[E1_CODIMOV],
				[E1_FILDEB],
				[E1_NUMRA],
				[E1_NUMSOL],
				[E1_INSCRIC],
				[E1_SERREC],
				[E1_CODBAR],
				[E1_DATAEDI],
				[E1_CODDIG],
				[E1_CHQDEV],
				[E1_LIDESCF],
				[E1_VLBOLSA],
				[E1_NUMCRD],
				[E1_VLFIES],
				[E1_DEBITO],
				[E1_CCD],
				[E1_ITEMD],
				[E1_CLVLDB],
				[E1_CREDIT],
				[E1_CCC],
				[E1_ITEMC],
				[E1_CLVLCR],
				[E1_DESCON1],
				[E1_DESCON2],
				[E1_DTDESC3],
				[E1_DTDESC1],
				[E1_DTDESC2],
				[E1_VLMULTA],
				[E1_DESCON3],
				[E1_MOTNEG],
				[E1_SABTPIS],
				[E1_SABTCOF],
				[E1_SABTCSL],
				[E1_FORNISS],
				[E1_PARTOT],
				[E1_SITFAT],
				[E1_BASEPIS],
				[E1_BASECOF],
				[E1_BASECSL],
				[E1_VRETISS],
				[E1_PARCIRF],
				[E1_SCORGP],
				[E1_FRETISS],
				[E1_TXMDCOR],
				[E1_SATBIRF],
				[E1_TIPREG],
				[E1_CONEMP],
				[E1_VERCON],
				[E1_SUBCON],
				[E1_VERSUB],
				[E1_PLLOTE],
				[E1_PLOPELT],
				[E1_CODRDA],
				[E1_FORMREC],
				[E1_BCOCLI],
				[E1_AGECLI],
				[E1_CTACLI],
				[E1_PARCFET],
				[E1_FETHAB],
				[E1_MDCRON],
				[E1_MDCONTR],
				[E1_MEDNUME],
				[E1_MDPLANI],
				[E1_MDPARCE],
				[E1_MDREVIS],
				[E1_NUMMOV],
				[E1_PREFORI],
				[E1_NODIA],
				[E1_TITPAI],
				[E1_DOCTEF],
				[E1_MDMULT],
				[E1_JURFAT],
				[E1_MDBONI],
				[E1_MDDESC],
				[E1_RELATO],
				[E1_BASEINS],
				[E1_MULTDIA],
				[E1_NFELETR],
				[E1_RETCNTR],
				[E1_NUMCON],
				[E1_TURMA],
				[E1_IDLAN],
				[E1_NSUTEF],
				[E1_SABTIRF],
				[E1_IDAPLIC],
				[E1_PROCEL],
				[E1_NOPER],
				[E1_SERVICO],
				[E1_DIACTB],
				[E1_IDBOLET],
				[E1_VRETIRF],
				[E1_BASEISS],
				[E1_VLBOLP],
				[E1_APLVLMN],
				[E1_LTCXA],
				[E1_NUMINSC],
				[E1_CODISS],
				[E1_SEQBX],
				[E1_NUMPRO],
				[E1_INDPRO],
				[E1_FABOV],
				[E1_PARCFAB],
				[E1_FACS],
				[E1_PARCFAC],
				[E1_VLMINIS],
				[E1_TPDP],
				[E1_PARTPDP],
				[E1_IDMOV],
				[E1_PRINSS],
				[E1_TPDESC],
				[E1_RATFIN],
				[E1_CODIRRF],
				[E1_PRISS],
				[E1_PRODUTO],
				[E1_PERLET],
				[E1_CHAVENF],
				[E1_CTRBCO],
				[E1_DESCJUR],
				[E1_CCUSTO],
				[E1_FAMAD],
				[E1_FMPEQ],
				[E1_PARCFAM],
				[E1_PARCFMP],
				[E1_TPESOC],
				[E1_CNO],
				[E1_CDRETCS],
				[E1_CDRETIR],
				[E1_SDOC],
				[E1_SDOCREC],
				[E1_EC05DB],
				[E1_EC05CR],
				[E1_EC06DB],
				[E1_EC06CR],
				[E1_CODRET],
				[E1_CLVL],
				[E1_ITEMCTA],
				[E1_CONHTL],
				[E1_TCONHTL],
				[E1_BOLETO],
				[E1_EC07DB],
				[E1_EC07CR],
				[E1_EC08DB],
				[E1_EC08CR],
				[E1_EC09DB],
				[E1_EC09CR],
				[E1_VRETBIS],
				[E1_BTRISS],
				[E1_CODSERV],
				[E1_PARCIMA],
				[E1_IMA],
				[D_E_L_E_T_],
				[R_E_C_N_O_],
				[R_E_C_D_E_L_])
		VALUES (N'D MG 01 ',
				N'FIN',
				N'" . $i . "',
				N' ',
				N'NF ',
				N'001       ',
				N'   ',
				N'     ',
				N'001   ',
				N'01',
				N'1                   ',
				N'20200327',
				N'20200327',
				N'20200327',
				1500,
				0,
				0,
				0,
				N'               ',
				N'   ',
				N'20200327',
				N'      ',
				N'        ',
				N'20200327',
				N'                                        ',
				N' ',
				N'        ',
				N'                    ',
				N'20200327',
				N'              ',
				N'0',
				N'               ',
				0,
				N'      ',
				N'      ',
				N'      ',
				N'      ',
				N'      ',
				N'      ',
				0,
				0,
				0,
				0,
				0,
				0,
				0,
				0,
				0,
				1500,
				N'20200327',
				N'          ',
				0,
				0,
				1,
				0,
				0,
				0,
				0,
				0,
				N'   ',
				N'         ',
				N'5a',
				N'      ',
				N'     ',
				0,
				0,
				0,
				0,
				0,
				N'  ',
				N'  ',
				N'  ',
				N'      ',
				N'        ',
				0,
				1500,
				N'        ',
				N'         ',
				N'   ',
				N'B',
				N'FINA040 ',
				N'      ',
				N'                   ',
				N'S',
				0,
				0,
				N'1',
				N'                ',
				N'        ',
				N'      ',
				N'   ',
				0,
				N'               ',
				N'   ',
				N'     ',
				N'          ',
				N'      ',
				N'      ',
				N'      ',
				0,
				N'D MG 01 ',
				N'        ',
				N'   ',
				N'   ',
				0,
				0,
				0,
				N' ',
				N'  ',
				N'    ',
				N'            ',
				N'    ',
				N'    ',
				N'      ',
				0,
				0,
				0,
				0,
				0,
				N'2',
				N'D MG 01 ',
				N'T1',
				N'2',
				N'2',
				N'                                                  ',
				N'1',
				N'                                        ',
				N'          ',
				N'            ',
				N' ',
				N'      ',
				N' ',
				N'        ',
				N'            ',
				N'        ',
				N'               ',
				N'      ',
				N'          ',
				N'   ',
				N'                                            ',
				N'        ',
				N'                                                ',
				N' ',
				N'        ',
				0,
				N'          ',
				0,
				N'                    ',
				N'         ',
				N'         ',
				N'         ',
				N'                    ',
				N'         ',
				N'         ',
				N'         ',
				0,
				0,
				N'        ',
				N'        ',
				N'        ',
				0,
				0,
				N'   ',
				0,
				0,
				0,
				N'      ',
				N'    ',
				N' ',
				0,
				0,
				0,
				0,
				N' ',
				N'2',
				N' ',
				0,
				0,
				N'  ',
				N'            ',
				N'   ',
				N'         ',
				N'   ',
				N'          ',
				N'    ',
				N'      ',
				N'  ',
				N'   ',
				N'     ',
				N'          ',
				N' ',
				0,
				N'      ',
				N'               ',
				N'      ',
				N'      ',
				N' ',
				N'   ',
				N'  ',
				N'   ',
				N'          ',
				N'                                                  ',
				N'                    ',
				0,
				N'                                                  ',
				0,
				0,
				N'2',
				0,
				0,
				N'                    ',
				0,
				N'                    ',
				N'                    ',
				0,
				N'            ',
				0,
				0,
				0,
				0,
				N'          ',
				N'  ',
				0,
				0,
				0,
				0,
				N'1',
				N'          ',
				0,
				N'      ',
				N'  ',
				N'          ',
				N' ',
				0,
				N' ',
				0,
				N' ',
				N'1',
				0,
				N' ',
				N'          ',
				0,
				N'C',
				N'2',
				N'    ',
				0,
				N'                              ',
				N'    ',
				N'            ',
				N'                                                  ',
				0,
				N'         ',
				0,
				0,
				N' ',
				N' ',
				N'  ',
				N'      ',
				N'    ',
				N'    ',
				N'   ',
				N'   ',
				N'      ',
				N'      ',
				N'      ',
				N'      ',
				N'    ',
				N'         ',
				N'         ',
				N'                                ',
				N'3',
				N' ',
				N'      ',
				N'      ',
				N'      ',
				N'      ',
				N'      ',
				N'      ',
				0,
				0,
				N'         ',
				N' ',
				0,
				N' ',
				" . $recno . ",
				0)
		");

        echo "SE1: $i / OK \n";
    } catch (Exception $e) {
        echo 'Erro: ' . $e;
    }

    try {
        $sql->query("
		INSERT [dbo].[SE5T10]
				([E5_FILIAL],
				[E5_DATA],
				[E5_TIPO],
				[E5_MOEDA],
				[E5_VALOR],
				[E5_NATUREZ],
				[E5_BANCO],
				[E5_AGENCIA],
				[E5_CONTA],
				[E5_NUMCHEQ],
				[E5_DOCUMEN],
				[E5_VENCTO],
				[E5_RECPAG],
				[E5_BENEF],
				[E5_HISTOR],
				[E5_TIPODOC],
				[E5_VLMOED2],
				[E5_LA],
				[E5_SITUACA],
				[E5_LOTE],
				[E5_PREFIXO],
				[E5_NUMERO],
				[E5_PARCELA],
				[E5_CLIFOR],
				[E5_LOJA],
				[E5_DTDIGIT],
				[E5_TIPOLAN],
				[E5_DEBITO],
				[E5_CREDITO],
				[E5_MOTBX],
				[E5_RATEIO],
				[E5_RECONC],
				[E5_SEQ],
				[E5_DTDISPO],
				[E5_CCD],
				[E5_CCC],
				[E5_OK],
				[E5_ARQRAT],
				[E5_IDENTEE],
				[E5_ORDREC],
				[E5_FILORIG],
				[E5_ARQCNAB],
				[E5_VLJUROS],
				[E5_VLMULTA],
				[E5_VLCORRE],
				[E5_VLDESCO],
				[E5_CNABOC],
				[E5_SITUA],
				[E5_ITEMD],
				[E5_ITEMC],
				[E5_CLVLDB],
				[E5_CLVLCR],
				[E5_PROJPMS],
				[E5_EDTPMS],
				[E5_TASKPMS],
				[E5_MODSPB],
				[E5_FATURA],
				[E5_TXMOEDA],
				[E5_FATPREF],
				[E5_CODORCA],
				[E5_SITCOB],
				[E5_FORNADT],
				[E5_LOJAADT],
				[E5_CLIENTE],
				[E5_FORNECE],
				[E5_SERREC],
				[E5_OPERAD],
				[E5_MOVCX],
				[E5_KEY],
				[E5_MULTNAT],
				[E5_AGLIMP],
				[E5_VLACRES],
				[E5_VLDECRE],
				[E5_VRETPIS],
				[E5_VRETCOF],
				[E5_VRETCSL],
				[E5_PRETPIS],
				[E5_PRETCOF],
				[E5_PRETCSL],
				[E5_AUTBCO],
				[E5_PRETIRF],
				[E5_VRETIRF],
				[E5_VRETISS],
				[E5_NUMMOV],
				[E5_PROCTRA],
				[E5_BASEIRF],
				[E5_NODIA],
				[E5_ORIGEM],
				[E5_DIACTB],
				[E5_FORMAPG],
				[E5_FLDMED],
				[E5_PRINSS],
				[E5_TPDESC],
				[E5_CGC],
				[E5_PRISS],
				[E5_IDMOVI],
				[E5_DTCANBX],
				[E5_PRETINS],
				[E5_VRETINS],
				[E5_CCUSTO],
				[E5_SEQCON],
				[E5_MOVFKS],
				[E5_IDORIG],
				[E5_TABORI],
				[E5_SDOCREC],
				[E5_EC05DB],
				[E5_EC05CR],
				[E5_EC06DB],
				[E5_EC06CR],
				[E5_MSFIL],
				[E5_EC07DB],
				[E5_EC07CR],
				[E5_EC08DB],
				[E5_EC08CR],
				[E5_EC09DB],
				[E5_EC09CR],
				[D_E_L_E_T_],
				[R_E_C_N_O_],
				[R_E_C_D_E_L_])
		VALUES (N'D MG 01 ',
				N'20200327',
				N'NF ',
				N'01',
				1500,
				N'001       ',
				N'CX1',
				N'00001',
				N'0000000001',
				N'               ',
				N'                                                  ',
				N'20200327',
				N'R',
				N'1                             ',
				N'Valor recebido s/ Titulo                ',
				N'VL',
				1500,
				N'N ',
				N' ',
				N'        ',
				N'FIN',
				N'" . $i . "',
				N' ',
				N'001   ',
				N'01',
				N'20200327',
				N' ',
				N'                    ',
				N'                    ',
				N'NOR',
				N' ',
				N' ',
				N'01',
				N'20200327',
				N'         ',
				N'         ',
				N'  ',
				N'                                                  ',
				N'      ',
				N'      ',
				N'D MG 01 ',
				N'            ',
				0,
				0,
				0,
				0,
				N'  ',
				N'  ',
				N'         ',
				N'         ',
				N'         ',
				N'         ',
				N'          ',
				N'            ',
				N'            ',
				N' ',
				N'         ',
				1,
				N'   ',
				N'        ',
				N'0',
				N'      ',
				N'  ',
				N'001   ',
				N'      ',
				N'   ',
				N'      ',
				N' ',
				N'                                                  ',
				N'2',
				N'         ',
				0,
				0,
				0,
				0,
				0,
				N' ',
				N' ',
				N' ',
				N'                         ',
				N' ',
				0,
				0,
				N'  ',
				N'                    ',
				0,
				N'          ',
				N'FINA740 ',
				N'  ',
				N'     ',
				N' ',
				0,
				N'I',
				N'              ',
				0,
				N'          ',
				N'        ',
				N' ',
				0,
				N'         ',
				N'          ',
				N'S',
				N'',
				N'',
				N'   ',
				N'      ',
				N'      ',
				N'      ',
				N'      ',
				N'D MG 01 ',
				N'      ',
				N'      ',
				N'      ',
				N'      ',
				N'      ',
				N'      ',
				N' ',
				" . $recno . ",
				0)
		");

        echo "SE5: $i / OK \n";
    } catch (Exception $e) {
        echo 'Erro: ' . $e;
    }

    echo "\n\n";
}
